name: release

on:
  workflow_run:
    workflows: [ "test" ]
    branches: [ main ]
    paths:
      - ".github/workflows/test.yml"
    types:
      - completed

jobs:
  test-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: release
        run: |
          echo "release packages"