name: release

on:
  push:
    paths:
      - ".github/workflows/release.yml"

jobs:
  test-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: release
        run: |
          echo "release packages"