name: test

on: [push, pull_request]

jobs:
  test-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test packages
        run: |
          echo "test packages"

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '.github/workflows/test.yml'
      - name: release
        if: steps.changes.outputs.src == 'true'
        run: |
          echo "release packages"