name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.get_env.outputs.env }}
    steps:
      - id: get_env
        run: |
          if [[ '${{ github.head_ref || github.ref_name }}' == 'main' ]]; then
            echo "env=production" >> $GITHUB_OUTPUT # TODO replace with Production when infrastructure is ready
          elif [[ '${{ github.head_ref || github.ref_name }}' == 'uat' ]]; then
            # TODO
            echo "env=acceptance" >> $GITHUB_OUTPUT # TODO replace with Acceptance when infrastructure is ready
          elif [[ '${{ github.head_ref || github.ref_name }}' == 'dev' ]]; then
            echo "env=Development" >> $GITHUB_OUTPUT
          else
            echo "Unknown environment: ${{ github.head_ref || github.ref_name }}"
            exit 1
          fi

  test-packages:
    runs-on: ubuntu-latest
    needs: [ init ]
    steps:
      - uses: actions/checkout@v1
      - name: test packages
        run: |
          echo "test packages"

      - name: echo env
        run: |
          echo ${{needs.init.outputs.environment}}

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - '.github/workflows/test.yml'
      - name: release
        if: steps.changes.outputs.src == 'true'
        run: |
          echo "release packages"